//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportToSRP3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityStudyItemIndividual
    {
        public long Id { get; set; }
        public byte IndividualType { get; set; }
        public byte IndividualRole { get; set; }
        public bool IsCurrent { get; set; }
        public bool IsCompleted { get; set; }
        public string DisplayEndDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public long IndividualId { get; set; }
        public Nullable<long> ActivityId { get; set; }
        public Nullable<long> StudyItemId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime LastUpdatedTimestamp { get; set; }
        public System.Guid LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> ImportedTimestamp { get; set; }
        public Nullable<System.Guid> ImportedFrom { get; set; }
        public string ImportedFileType { get; set; }
        public Nullable<long> ActivityStudyItemId { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual ActivityStudyItem ActivityStudyItem { get; set; }
        public virtual Individual Individual { get; set; }
        public virtual StudyItem StudyItem { get; set; }
    }
}
