//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportToSRP3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cluster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cluster()
        {
            this.ClusterAuxiliaryBoardMembers = new HashSet<ClusterAuxiliaryBoardMember>();
            this.Cycles = new HashSet<Cycle>();
            this.Localities = new HashSet<Locality>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string LatinName { get; set; }
        public string StageOfDevelopment { get; set; }
        public Nullable<int> GeographicSize { get; set; }
        public string GeographicSizeUnit { get; set; }
        public Nullable<int> TotalPopulation { get; set; }
        public Nullable<int> ChildrenClassCoordinators { get; set; }
        public Nullable<int> JuniorYouthGroupCoordinators { get; set; }
        public Nullable<int> StudyCircleCoordinators { get; set; }
        public string Comments { get; set; }
        public long RegionId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime LastUpdatedTimestamp { get; set; }
        public System.Guid LastUpdatedBy { get; set; }
        public Nullable<System.Guid> ImportedFrom { get; set; }
        public Nullable<System.DateTime> ImportedTimestamp { get; set; }
        public string ImportedFileType { get; set; }
        public System.Guid GUID { get; set; }
        public string LegacyId { get; set; }
        public string InstituteId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClusterAuxiliaryBoardMember> ClusterAuxiliaryBoardMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cycle> Cycles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Locality> Localities { get; set; }
        public virtual Region Region { get; set; }
    }
}
