//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportToSRP3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cycle
    {
        public long Id { get; set; }
        public string DisplayStartDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public string DisplayEndDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> FriendsParticipatingInExpansionPhase { get; set; }
        public Nullable<int> CompletedBook1 { get; set; }
        public Nullable<int> CompletedBook2 { get; set; }
        public Nullable<int> CompletedBook3G1 { get; set; }
        public Nullable<int> CompletedBook3G2 { get; set; }
        public Nullable<int> CompletedBook3G3 { get; set; }
        public Nullable<int> CompletedBook4 { get; set; }
        public Nullable<int> CompletedBook5 { get; set; }
        public Nullable<int> CompletedBook6 { get; set; }
        public Nullable<int> CompletedBook7 { get; set; }
        public Nullable<int> CompletedBook8 { get; set; }
        public Nullable<int> CompletedBook9U1 { get; set; }
        public Nullable<int> CompletedBook9U2 { get; set; }
        public Nullable<int> CompletedBook11U1 { get; set; }
        public bool IsOverrideCompletedBookData { get; set; }
        public Nullable<int> DevotionalMeetingsNumber { get; set; }
        public Nullable<int> DevotionalMeetingsAttendance { get; set; }
        public Nullable<int> DevotionalMeetingsFriendsOfFaith { get; set; }
        public bool IsOverrideDevotionalMeetingsData { get; set; }
        public Nullable<int> ChildrenClassesNumber { get; set; }
        public Nullable<int> ChildrenClassesAttendance { get; set; }
        public Nullable<int> ChildrenClassesFriendsOfFaith { get; set; }
        public bool IsOverrideChildrenClassesDate { get; set; }
        public Nullable<int> JuniorYouthGroupsNumber { get; set; }
        public Nullable<int> JuniorYouthGroupsAttendance { get; set; }
        public Nullable<int> JuniorYouthGroupsFriendsOfFaith { get; set; }
        public bool IsOverrideJuniorYouthGroupsData { get; set; }
        public Nullable<int> StudyCirclesNumber { get; set; }
        public Nullable<int> StudyCirclesAttendance { get; set; }
        public Nullable<int> StudyCirclesFriendsOfFaith { get; set; }
        public bool IsOverrideStudyCirclesData { get; set; }
        public Nullable<int> ChildrenAndJuniorYouthRegisteredDuringCycle { get; set; }
        public Nullable<int> YouthAndAdultsEnrolledDuringCycle { get; set; }
        public Nullable<int> NewlyEnrolledBelieversInInstituteProcess { get; set; }
        public bool IsOverrideExpansionDuringCycleData { get; set; }
        public Nullable<int> BahaiChildren { get; set; }
        public Nullable<int> BahaiJuniorYouth { get; set; }
        public Nullable<int> BahaiYouth { get; set; }
        public Nullable<int> BahaiAdultMen { get; set; }
        public Nullable<int> BahaiAdultWomen { get; set; }
        public Nullable<int> TotalBahaiBelievers { get; set; }
        public bool IsOverrideBahaiPopulationData { get; set; }
        public Nullable<int> HomesVisitedForDeepening { get; set; }
        public Nullable<int> LocalitiesInNineteenDayFeastHeld { get; set; }
        public Nullable<int> NineteenDayFeastAttendanceEstimated { get; set; }
        public Nullable<int> LocalitiesObservedOneOrMoreHolyDays { get; set; }
        public Nullable<int> HolyDayAttendanceEstimated { get; set; }
        public bool IsOverrideCommunityDevelopmentData { get; set; }
        public long ClusterId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime LastUpdatedTimestamp { get; set; }
        public System.Guid LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> ImportedTimestamp { get; set; }
        public Nullable<System.Guid> ImportedFrom { get; set; }
        public string ImportedFileType { get; set; }
        public bool IsCycleDateChanged { get; set; }
        public bool IsLocalityDataChanged { get; set; }
        public bool IsRecalculated { get; set; }
        public System.Guid GUID { get; set; }
        public string LegacyId { get; set; }
        public string InstituteId { get; set; }
        public string Comments { get; set; }
        public Nullable<int> CompletedBook10 { get; set; }
    
        public virtual Cluster Cluster { get; set; }
    }
}
