//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportToSRP3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBScriptHistory
    {
        public long Id { get; set; }
        public string ScriptName { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
