//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportToSRP3
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualEmail
    {
        public long Id { get; set; }
        public string Email { get; set; }
        public short Order { get; set; }
        public long IndividualId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime LastUpdatedTimestamp { get; set; }
        public System.Guid LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> ImportedTimestamp { get; set; }
        public Nullable<System.Guid> ImportedFrom { get; set; }
        public string ImportedFileType { get; set; }
    
        public virtual Individual Individual { get; set; }
    }
}
