//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportToSRP3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListSortColumn
    {
        public long Id { get; set; }
        public string SortDirection { get; set; }
        public short Order { get; set; }
        public long ListId { get; set; }
        public long ListColumnId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime LastUpdatedTimestamp { get; set; }
        public System.Guid LastUpdatedBy { get; set; }
    
        public virtual ListColumn ListColumn { get; set; }
        public virtual List List { get; set; }
    }
}
