//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportToSRP3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListFilterColumn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListFilterColumn()
        {
            this.ListFilterColumns1 = new HashSet<ListFilterColumn>();
        }
    
        public long Id { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string Operator { get; set; }
        public string Value { get; set; }
        public short Order { get; set; }
        public long ListId { get; set; }
        public Nullable<long> ListColumnId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime LastUpdatedTimestamp { get; set; }
        public System.Guid LastUpdatedBy { get; set; }
    
        public virtual ListColumn ListColumn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListFilterColumn> ListFilterColumns1 { get; set; }
        public virtual ListFilterColumn ListFilterColumn1 { get; set; }
        public virtual List List { get; set; }
    }
}
