//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportToSRP3
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadDataFile
    {
        public long Id { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public System.DateTime FileDate { get; set; }
        public System.DateTime LoadedDate { get; set; }
        public string LoadedItem { get; set; }
        public Nullable<System.Guid> SourceApplicationGUID { get; set; }
        public string SourceApplicationVersion { get; set; }
        public string LoadedToLocation { get; set; }
    }
}
