//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportToSRP3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locality
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Locality()
        {
            this.Activities = new HashSet<Activity>();
            this.Individuals = new HashSet<Individual>();
            this.Subdivisions = new HashSet<Subdivision>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string LatinName { get; set; }
        public Nullable<bool> HasLocalSpiritualAssembly { get; set; }
        public Nullable<bool> HasLocalFund { get; set; }
        public Nullable<bool> IsObservesNineteenDayFeast { get; set; }
        public Nullable<int> NineteenDayFeastAttendance { get; set; }
        public Nullable<bool> IsObservesHolyDays { get; set; }
        public Nullable<int> HolyDayAttendance { get; set; }
        public Nullable<bool> HasDevotionalMeetings { get; set; }
        public Nullable<int> DevotionalMeetings { get; set; }
        public Nullable<int> DevotionalMeetingAttendance { get; set; }
        public Nullable<int> DevotionalMeetingFriendAttendance { get; set; }
        public Nullable<bool> IsConductsHomeVisits { get; set; }
        public Nullable<int> HomesVisited { get; set; }
        public string Comments { get; set; }
        public long ClusterId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime LastUpdatedTimestamp { get; set; }
        public System.Guid LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> ImportedTimestamp { get; set; }
        public Nullable<System.Guid> ImportedFrom { get; set; }
        public string ImportedFileType { get; set; }
        public System.Guid GUID { get; set; }
        public string LegacyId { get; set; }
        public string InstituteId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual Cluster Cluster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Individual> Individuals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subdivision> Subdivisions { get; set; }
    }
}
