//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportToSRP3
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalizedStudyItem
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Abbreviation { get; set; }
        public string StudyItemTypeName { get; set; }
        public long StudyItemId { get; set; }
        public string Language { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime LastUpdatedTimestamp { get; set; }
    
        public virtual StudyItem StudyItem { get; set; }
    }
}
