//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportToSRP3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SRP3Entities : DbContext
    {
        public SRP3Entities()
            : base("name=SRP3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityStudyItemIndividual> ActivityStudyItemIndividuals { get; set; }
        public virtual DbSet<ActivityStudyItem> ActivityStudyItems { get; set; }
        public virtual DbSet<ApplicationConfiguration> ApplicationConfigurations { get; set; }
        public virtual DbSet<ApplicationHistory> ApplicationHistories { get; set; }
        public virtual DbSet<ClusterAuxiliaryBoardMember> ClusterAuxiliaryBoardMembers { get; set; }
        public virtual DbSet<Cluster> Clusters { get; set; }
        public virtual DbSet<Cycle> Cycles { get; set; }
        public virtual DbSet<DBScriptHistory> DBScriptHistories { get; set; }
        public virtual DbSet<IndividualEmail> IndividualEmails { get; set; }
        public virtual DbSet<IndividualPhone> IndividualPhones { get; set; }
        public virtual DbSet<Individual> Individuals { get; set; }
        public virtual DbSet<ListColumn> ListColumns { get; set; }
        public virtual DbSet<ListDisplayColumn> ListDisplayColumns { get; set; }
        public virtual DbSet<ListFilterColumn> ListFilterColumns { get; set; }
        public virtual DbSet<List> Lists { get; set; }
        public virtual DbSet<ListSortColumn> ListSortColumns { get; set; }
        public virtual DbSet<LoadDataFile> LoadDataFiles { get; set; }
        public virtual DbSet<Locality> Localities { get; set; }
        public virtual DbSet<LocalizedStudyItem> LocalizedStudyItems { get; set; }
        public virtual DbSet<NationalCommunity> NationalCommunities { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<StudyItem> StudyItems { get; set; }
        public virtual DbSet<Subdivision> Subdivisions { get; set; }
    }
}
