//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportToSRP3
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudyItem()
        {
            this.ActivityStudyItemIndividuals = new HashSet<ActivityStudyItemIndividual>();
            this.ActivityStudyItems = new HashSet<ActivityStudyItem>();
            this.LocalizedStudyItems = new HashSet<LocalizedStudyItem>();
        }
    
        public long Id { get; set; }
        public Nullable<int> Number { get; set; }
        public byte ActivityType { get; set; }
        public string ActivityStudyItemType { get; set; }
        public int Sequence { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime LastUpdatedTimestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityStudyItemIndividual> ActivityStudyItemIndividuals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityStudyItem> ActivityStudyItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalizedStudyItem> LocalizedStudyItems { get; set; }
    }
}
