//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportToSRP3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subdivision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subdivision()
        {
            this.Activities = new HashSet<Activity>();
            this.Individuals = new HashSet<Individual>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string LatinName { get; set; }
        public string Comments { get; set; }
        public long LocalityId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime LastUpdatedTimestamp { get; set; }
        public System.Guid LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> ImportedTimestamp { get; set; }
        public Nullable<System.Guid> ImportedFrom { get; set; }
        public string ImportedFileType { get; set; }
        public System.Guid GUID { get; set; }
        public string LegacyId { get; set; }
        public string InstituteId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Individual> Individuals { get; set; }
        public virtual Locality Locality { get; set; }
    }
}
